apiVersion: 0.2.0
environments:
  default:
    destination:
      namespace: kubeflow-system
      server: https://10.0.0.8:6443
    k8sVersion: v1.11.2
    path: default
kind: ksonnet.io/app
libraries:
  argo:
    name: argo
    registry: kubeflow
    version: ""
  core:
    name: core
    registry: kubeflow
    version: ""
  examples:
    name: examples
    registry: kubeflow
    version: ""
  katib:
    name: katib
    registry: kubeflow
    version: ""
  mpi-job:
    name: mpi-job
    registry: kubeflow
    version: ""
  pytorch-job:
    name: pytorch-job
    registry: kubeflow
    version: ""
  seldon:
    name: seldon
    registry: kubeflow
    version: ""
  tf-serving:
    name: tf-serving
    registry: kubeflow
    version: ""
name: kubeflow_ks_app
registries:
  incubator:
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
  kubeflow:
    protocol: fs
    uri: /home/ericyeh/kubeflow/kubeflow_repo/kubeflow
version: 0.0.1
